# Project information
site_name: '2dados'
site_description: 'Projetos de Data Science e Machine Learning. Estudo de Cálculo.'
site_author: 'Carlos Andre'
site_url: 'https://www.2dados.com/'

# Navigation
pages:
  - Home: index.md
  - Sobre: sobre.md
  - Apoie: apoie.md
  - Consultoria: consultoria.md
  - App Web ebook:
    - Serviço: app_web_ebook/servico.md
    - App Web ebook - amostra: app_web_ebook/amostra.md
  - Diagramação:
    - Serviço: diagramacao/servico.md
    - Amostra: diagramacao/amostra-diagramacao.md
  - Ciência de dados:
    - Serviço: ciencia_de_dados/servico.md
    - Amostra 1: ciencia_de_dados/amostra-1.md
    - Amostra 2: ciencia_de_dados/amostra-2.md
  - Aprenda Cálculo:
    - Bem-Vindo(a)s: aprendacalculo/index.md
    - Pré-Cálculo: aprendacalculo/pre_calculo.md
    - Cálculo I: aprendacalculo/calculo_i.md
    - Cálculo II: aprendacalculo/calculo_ii.md
    - Cálculo III: aprendacalculo/calculo_iii.md
    - Cálculo IV: aprendacalculo/calculo_iv.md
    - C. Numérico: aprendacalculo/calculo_numerico.md
  - Curso de LaTeX:
    - Bem-Vindo(a)s: cursolatex/index.md
    - Programas: cursolatex/programas.md
    - LaTeX online: cursolatex/latex_online.md
    - Parte 1: cursolatex/parte_1.md
    - Parte 2: cursolatex/parte_2.md
    - Parte 3: cursolatex/parte_3.md
    - Parte 4: cursolatex/parte_4.md
    - Parte 5: cursolatex/parte_5.md
    - Parte 6: cursolatex/parte_6.md
    - Parte 7: cursolatex/parte_7.md
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'pt'
  feature:
    tabs: true
  logo: 'images/logo.png'
  palette:
    primary: 'Teal'
    accent: 'Teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: './docs/assets/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Equations
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Social
extra:
  social:
    - type: 'github'
      link: 'https://github.com/andhremattos'
    - type: 'facebook'
      link: 'https://www.facebook.com/2dhematos'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/dhematos'
    - type: 'instagram'
      link: 'https://www.instagram.com/dhematos'
    - type: 'twitter'
      link: 'https://www.twitter.com/dhematos'
    - type: 'whatsapp'
      link: 'https://api.whatsapp.com/send?1=pt_BR&phone=5575991940520'
    - type: 'telegram'
      link: 'https://t.me/dhematos'
 # disqus: 'deep-learning-wizard'


# Google Analytics
google_analytics:
  - 'UA-215083676-1'
  - 'auto'

# Copyright
copyright: '&copy; 2020 2dados'
