# Project information
site_name: '2dados'
site_description: 'Projetos de Data Science e Machine Learning. Estudo de Cálculo.'
site_author: 'Carlos Andre'
site_url: 'https://www.2dados.com/'

# Navigation
pages:
    - Home: index.md
    - Sobre: sobre.md
#    - Reviews: review.md
    - Projetos: projetos.md
    - Consultoria: consultoria.md
    - Pré-Cálculo:
      - Introdução: pre_calculo/introducao.md
      - Conjuntos: pre_calculo/conjuntos_numericos/introducao_a_conjuntos.md
      - Funções: pre_calculo/funcoes/introducao_a_funcao.md
  

    - Cálculo I:
      - Introdução: calculo_i/introducao.md
      - Limite: calculo_i/limite/parte_1.md
      - Derivada: calculo_i/derivada/parte_1.md
      

    - Cálculo II:
      - Introdução: calculo_ii/introducao.md
      - Integral: calculo_ii/integral/parte_1.md

    - Blog:
      - Home: blog/index.md
      - Artigo_1: blog/artigo_01_12_02_2020.md
      - Artigo_2: blog/artigo_02_14_02_2020.md

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'pt'
  feature:
    tabs: true
  logo:
    icon: 'whatshot'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: './docs/assets/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Equations
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Social
extra:
  social:
    - type: 'github'
      link: 'https://github.com/andhremattos'
    - type: 'facebook'
      link: 'https://www.facebook.com/acmatos/'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/andhremattos/'
  disqus: 'deep-learning-wizard'


# Google Analytics
google_analytics:
  - 'UA-122083328-1'
  - 'auto'

# Copyright
copyright: '&copy; 2019 2dados. "Deus não joga dados" (Albert Einstein).'
